import { ProtectableType, RiskCard, RiskType } from "@/types/game.types";

// Карты рисков
export const RISK_CARDS: RiskCard[] = [
  {
    id: 'minor_accident',
    type: RiskType.CAR_ACCIDENT,
    name: 'Легкое ДТП',
    damage: 200,
    speed: 8, // Чем меньше, тем быстрее
    target: ProtectableType.CAR,
    description: 'Мелкое ДТП с небольшими повреждениями.',
    imageUrl: '/car-crash.svg',
  },
  {
    id: 'major_accident',
    type: RiskType.CAR_ACCIDENT,
    name: 'Серьезное ДТП',
    damage: 400,
    speed: 12,
    target: ProtectableType.CAR,
    description: 'Серьезная авария с крупным ущербом.',
    imageUrl: '/car-crash.svg',
    specialEffect: 'Может повредить и членов семьи',
  },
  {
    id: 'house_fire',
    type: RiskType.FIRE,
    name: 'Пожар в доме',
    damage: 600,
    speed: 15,
    target: ProtectableType.HOUSE,
    description: 'Пожар в квартире с серьезными повреждениями.',
    imageUrl: '/fire.svg',
    specialEffect: 'Распространяется на соседние объекты',
  },
  {
    id: 'illness',
    type: RiskType.ILLNESS,
    name: 'Болезнь',
    damage: 300,
    speed: 10,
    target: ProtectableType.FAMILY,
    description: 'Заболевание, требующее серьезного лечения.',
    imageUrl: '/virus.svg',
  },
  {
    id: 'apartment_flood',
    type: RiskType.FLOOD,
    name: 'Затопление',
    damage: 250,
    speed: 8,
    target: ProtectableType.HOUSE,
    description: 'Прорыв трубы и затопление квартиры.',
    imageUrl: '/water.svg',
  },
  {
    id: 'theft',
    type: RiskType.THEFT,
    name: 'Кража',
    damage: 400,
    speed: 5, // Очень быстрая
    target: ProtectableType.HOUSE,
    description: 'Ограбление квартиры.',
    imageUrl: '/theft.svg',
    specialEffect: 'Игнорирует часть защиты',
  },
  {
    id: 'car_theft',
    type: RiskType.THEFT,
    name: 'Угон',
    damage: 800,
    speed: 6,
    target: ProtectableType.CAR,
    description: 'Угон автомобиля.',
    imageUrl: '/car-theft.svg',
  },
  {
    id: 'fraud',
    type: RiskType.FRAUD,
    name: 'Мошенничество',
    damage: 400,
    speed: 4, // Самая быстрая
    target: ProtectableType.WORK,
    description: 'Финансовое мошенничество.',
    imageUrl: '/fraud.svg',
    specialEffect: 'Может атаковать любую цель',
  },
];